In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\include']


In [3]:
arr = np.zeros(100)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [4]:
arr = np.zeros((100,100))
#print(arr)
print("%d bytes" % (arr.size * arr.itemsize))

80000 bytes


In [5]:
arr = np.zeros(10)
arr[5] = 1
print(arr)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [6]:
arr = np.arange(0,30)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [7]:
arr = arr[::-1]
print(arr)

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]


In [8]:
arr = np.arange(12)
arr = arr.reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
arr = np.nonzero([0,0,1,2,3,1,10,0,0,1,2,3,10,1])
print(arr)

(array([ 2,  3,  4,  5,  6,  9, 10, 11, 12, 13], dtype=int64),)


In [10]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.21069391 0.74964389 0.6930656 ]
  [0.87458437 0.47348539 0.72766331]
  [0.3939478  0.11351463 0.20742699]]

 [[0.68434051 0.40955646 0.67127346]
  [0.83462585 0.38989027 0.94950569]
  [0.71838161 0.37329399 0.33234579]]

 [[0.35790062 0.61121257 0.48796176]
  [0.41455996 0.17394995 0.82623845]
  [0.76735222 0.95159751 0.57679183]]]


In [12]:
arr = np.random.random((10,10,10))
arr_min, arr_max = arr.min(), arr.max()
#print(arr)
print(arr_min, arr_max)

0.0027965580664272016 0.997521805800632


In [13]:
arr = np.random.random(30)
mean = arr.mean() #среднее
print(mean)

0.5852327283646641


In [14]:
arr = np.ones((10,10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
#arr = np.zeros((5,5))
#arr[1:-1, 1:-1] = 1
arr = np.ones((5,5))
arr = np.pad(arr, pad_width = 1, mode = 'constant', constant_values= 0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [17]:
arr = np.diag(1+np.arange(4), k = -1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [18]:
arr = np.zeros((8,8))
arr[1::2,::2 ] = 1 #1 -[с какой начинается :: интервал, :] 
arr[::2, 1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [19]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [20]:
arr = np.tile(np.array([[1,0],[0,1]]), (4,4)) #повторяет какой либо массив 4х4 раза
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [21]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
print(arr)

[[ 0.81596001  1.06190416  1.06034175  1.44203771 -1.22605449]
 [ 1.30204145 -0.56341847 -1.66711951  1.08663916 -0.50437271]
 [-0.28810446  0.98362492  0.65407617 -0.79746026  0.73360691]
 [-0.32717833 -1.7155593   0.63634097 -0.34645725 -0.42616259]
 [-1.47358229 -0.05564125 -1.64660364  0.93226294  0.3288784 ]]


In [22]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-22-5432efe93e2f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [23]:
arr1 = np.array([[1,2,3],[13,4,3],[1,5,6], [1,8,9], [0,2,11]])
arr2 = np.array([[1,9],[0,2], [98,1]])


arr = np.dot(arr1,arr2)
print(arr)

[[ 295   16]
 [ 307  128]
 [ 589   25]
 [ 883   34]
 [1078   15]]


In [24]:
arr = np.arange(11)

arr[(3<arr)&(arr<=8)]*=-1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [25]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [26]:
Z = np.array(100)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>ZeroDivisionError

False

In [27]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-27-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-27-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [28]:
arr = np.random.uniform(-10,+10,10)
print(arr)
print (np.copysign(np.ceil(np.abs(arr)), arr))

[ 6.33557867  0.25584471  6.91229844 -1.36388236 -1.05498896  9.6298834
 -5.78618304  5.39090379  4.41698407 -6.93408247]
[ 7.  1.  7. -2. -2. 10. -6.  6.  5. -7.]


In [30]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

print(arr1, arr2)
print(np.intersect1d(arr1,arr2))

[9 2 1 6 5 6 2 1 4 2] [7 0 0 4 9 4 7 6 5 0]
[4 5 6 9]


In [31]:

defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0


_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-31-efc4639271dd>, line 7)

In [33]:
np.sqrt(-1) == np.emath.sqrt(-1)
print(np.sqrt(-1),np.emath.sqrt(-1) )

nan 1j


<ipython-input-33-8a1c3b0c741f>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)
<ipython-input-33-8a1c3b0c741f>:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1),np.emath.sqrt(-1) )


In [36]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday, today, tomorrow)

2021-10-13 2021-10-14 2021-10-15


In [37]:
data = np.arange('1999-08', '1999-09', dtype = 'datetime64[D]')
print(data)

['1999-08-01' '1999-08-02' '1999-08-03' '1999-08-04' '1999-08-05'
 '1999-08-06' '1999-08-07' '1999-08-08' '1999-08-09' '1999-08-10'
 '1999-08-11' '1999-08-12' '1999-08-13' '1999-08-14' '1999-08-15'
 '1999-08-16' '1999-08-17' '1999-08-18' '1999-08-19' '1999-08-20'
 '1999-08-21' '1999-08-22' '1999-08-23' '1999-08-24' '1999-08-25'
 '1999-08-26' '1999-08-27' '1999-08-28' '1999-08-29' '1999-08-30'
 '1999-08-31']


In [38]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [40]:
arr = np.random.uniform(0,10,10)
#print(arr)

print (arr - arr%1)
print (np.floor(arr))
print (np.ceil(arr)-1)
print (arr.astype(int))
print (np.trunc(arr))

[1. 8. 4. 5. 5. 4. 8. 8. 5. 9.]
[1. 8. 4. 5. 5. 4. 8. 8. 5. 9.]
[1. 8. 4. 5. 5. 4. 8. 8. 5. 9.]
[1 8 4 5 5 4 8 8 5 9]
[1. 8. 4. 5. 5. 4. 8. 8. 5. 9.]


In [46]:
arr = np.zeros((5,5))
#for i in range(5):
    #arr[i] = np.arange(5)
arr+=np.arange(5)    
   
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [47]:
def generate():
    for x in range(10):
        yield x
arr = np.fromiter(generate(),dtype=float,count=-1) #оздайте новый одномерный массив из итерируемого объекта.
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [50]:
arr = np.linspace(0,1,11,endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [51]:
arr = np.random.random(10)
arr.sort()
print(arr)

[0.10259751 0.23087163 0.45447035 0.47128574 0.61876841 0.63616001
 0.73937114 0.84513296 0.87967604 0.91346505]


In [3]:
arr = np.arange(10)
print(arr)
print(np.add.reduce(arr))


[0 1 2 3 4 5 6 7 8 9]
45


In [6]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

print("Форма -",np.allclose(arr1,arr2))
print("Значение -",np.array_equal(arr1,arr2))

Форма - False
Значение - False


In [7]:
arr = np.zeros(10)
arr.flags.writeable = False
arr[0] = 1

ValueError: assignment destination is read-only

In [16]:
mx = np.random.random((10,2))

print(mx)
X,Y = mx[:,0],mx[:,1] 

R = np.sqrt(X**2+Y**2)
T = np.arctan2(X,Y)
print(R,T)

mx[:,0], mx[:,1] = R,T
print(mx)

[[0.03912312 0.50055495]
 [0.68721046 0.0169286 ]
 [0.26543218 0.9562529 ]
 [0.3703807  0.11228856]
 [0.23086002 0.21389533]
 [0.18662366 0.15107566]
 [0.45137025 0.74566128]
 [0.81508854 0.88251099]
 [0.46931999 0.59493878]
 [0.43219027 0.37678542]]
[0.50208155 0.68741894 0.99240811 0.38702788 0.31471822 0.24010882
 0.87163401 1.2013305  0.7577687  0.5733722 ] [0.07800091 1.54616751 0.27075886 1.27643322 0.82352355 0.89027716
 0.54432853 0.74570268 0.66790771 0.85377904]
[[0.50208155 0.07800091]
 [0.68741894 1.54616751]
 [0.99240811 0.27075886]
 [0.38702788 1.27643322]
 [0.31471822 0.82352355]
 [0.24010882 0.89027716]
 [0.87163401 0.54432853]
 [1.2013305  0.74570268]
 [0.7577687  0.66790771]
 [0.5733722  0.85377904]]


In [18]:
arr = np.random.random(5)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[0.60464971 0.75268092 0.04163541 0.40412845 0.49628537]
[0.60464971 0.         0.04163541 0.40412845 0.49628537]


In [20]:
arr = np.zeros((5,5), [('x',float),('y',float)])
print(arr)
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(arr)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [26]:
X = np.random.randint(0,10,10)
Y = np.random.randint(0,10,10)
print(X,Y)

print(np.subtract.outer(X,Y))
C = 1.0/np.subtract.outer(X,Y)
print(C)

[3 6 1 7 2 9 2 1 6 9] [5 8 8 5 1 3 3 9 5 8]
[[-2 -5 -5 -2  2  0  0 -6 -2 -5]
 [ 1 -2 -2  1  5  3  3 -3  1 -2]
 [-4 -7 -7 -4  0 -2 -2 -8 -4 -7]
 [ 2 -1 -1  2  6  4  4 -2  2 -1]
 [-3 -6 -6 -3  1 -1 -1 -7 -3 -6]
 [ 4  1  1  4  8  6  6  0  4  1]
 [-3 -6 -6 -3  1 -1 -1 -7 -3 -6]
 [-4 -7 -7 -4  0 -2 -2 -8 -4 -7]
 [ 1 -2 -2  1  5  3  3 -3  1 -2]
 [ 4  1  1  4  8  6  6  0  4  1]]
[[-0.5        -0.2        -0.2        -0.5         0.5                inf
          inf -0.16666667 -0.5        -0.2       ]
 [ 1.         -0.5        -0.5         1.          0.2         0.33333333
   0.33333333 -0.33333333  1.         -0.5       ]
 [-0.25       -0.14285714 -0.14285714 -0.25               inf -0.5
  -0.5        -0.125      -0.25       -0.14285714]
 [ 0.5        -1.         -1.          0.5         0.16666667  0.25
   0.25       -0.5         0.5        -1.        ]
 [-0.33333333 -0.16666667 -0.16666667 -0.33333333  1.         -1.
  -1.         -0.14285714 -0.33333333 -0.16666667]
 [ 0.25        1.    

<ipython-input-26-19a48a744776>:6: RuntimeWarning: divide by zero encountered in true_divide
  C = 1.0/np.subtract.outer(X,Y)


In [27]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [38]:
#вывод числе с плавоющей точкой
np.set_printoptions(threshold=10)
Z = np.zeros((5,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
#Найти ближайший элемент массива к числу
arr = np.arange(10)
print(arr)
v = np.random.uniform(0,10)
print(v)
index = (np.abs(arr-v)).argmin()
print(arr[index])

[0 1 2 ... 7 8 9]
4.712314828375747
5


In [42]:
arr = np.zeros(10, [('koordinats',[('x', float,1), ('y', float, 1)]),
                    ('color',[('r', float,1),
                              ('b', float, 1),
                              ('g', float,1)])])
print(arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-42-601abac7313f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  arr = np.zeros(10, [('koordinats',[('x', float,1), ('y', float, 1)]),


In [51]:

#Найти растояние между точками
arr = np.random.random((10,2))
print(arr)

X,Y = arr[:,0], arr[:,1]
print(X,Y)

D = np.sqrt(X**2+Y**2)
D2 = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print("D1 ",D)
print("D2 ", D2)


import scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.89805651 0.77941781]
 [0.922091   0.88513452]
 [0.97567582 0.72161638]
 ...
 [0.77425692 0.7723577 ]
 [0.12460708 0.20067824]
 [0.74711234 0.17000031]]
[0.89805651 0.922091   0.97567582 0.01172815 0.73834341 0.11145368
 0.43610481 0.77425692 0.12460708 0.74711234] [0.77941781 0.88513452 0.72161638 0.36678413 0.38839552 0.39405842
 0.26127901 0.7723577  0.20067824 0.17000031]
D1  [1.18911631 1.27816859 1.2135376  0.36697159 0.83426738 0.40951674
 0.50838384 1.09362251 0.23621744 0.76620947]
D2  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0.         0.76197249 0.65813389 ... 0.54264042 0.65481722 0.61528625]
 [0.76197249 0.         0.61022984 ... 0.57186886 0.5282975  0.27455043]
 [0.65813389 0.61022984 0.         ... 0.11693375 0.0835029  0.33997131]
 ...
 [0.54264042 0.57186886 0.11693375 ... 0.         0.12607368 0.29813356]
 [0.65481722 0.5282975  0.0835029  ... 0.12607368 0.         0.2609501 ]
 [0.61528625 0.27455043 0.33997131 ... 0.29813356 0.2609501  0.        ]]


In [52]:
#Изменить тип данных
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-54-4a7b0d9b8ca3>:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


In [57]:
arr = np.arange(9).reshape(3,3)
print(arr)
for index, value in np.ndenumerate(arr):
    print(index, value)
for index in np.ndindex(arr.shape):
    print(index, arr[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [62]:
X,Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))

D = np.sqrt(X,Y)

sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[       nan        nan        nan ... 0.75746513 0.67780958 0.60653066]
 [       nan        nan        nan ... 0.75746513 0.67780958 0.60653066]
 [       nan        nan        nan ... 0.75746513 0.67780958 0.60653066]
 ...
 [       nan        nan        nan ... 0.75746513 0.67780958 0.60653066]
 [       nan        nan        nan ... 0.75746513 0.67780958 0.60653066]
 [       nan        nan        nan ... 0.75746513 0.67780958 0.60653066]]


<ipython-input-62-7b3226622841>:3: RuntimeWarning: invalid value encountered in sqrt
  D = np.sqrt(X,Y)


In [69]:
n = 10
p = 3
arr = np.zeros((n,n))

np.put(arr,np.random.choice(range(n*n), p, replace=False),1)
print(arr)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [72]:
#Вычисление среднего значения каждой строки марицы
X = np.random.rand(5,10)
Y = X.mean(axis=1, keepdims=True)
print(Y)

[[0.62213655]
 [0.37933451]
 [0.40132827]
 [0.55032122]
 [0.53783042]]


In [87]:
#Сортировака мамссива по n-ому строкам
arr = np.random.randint(0,10,(3,3))
print(arr)
sort_mx = arr[arr[:,1].argsort()]
print(sort_mx)

[[0 0 2]
 [2 5 3]
 [4 0 7]]
[[0 0 2]
 [4 0 7]
 [2 5 3]]


In [88]:
#Определить есть ли нулевые столбцы
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [4]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]#flat - итератор по массиву
print(m)

0.4878409563744186


In [4]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A,B)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0]
 [1]
 [2]] [[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [11]:
class NameArray(np.ndarray):
    def __new__(cls,array,name = "np name"):
        obj = np.asarray(array).view(cls) #преобразвоание в массив numpy
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None:return
        self.info = getattr(obj, 'name', "no name")
        
        
arr = NameArray(np.arange(10), "range 10")
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[3. 2. 4. 6. 2. 3. 3. 3. 2. 2.]
[ 5.  3.  7. 11.  3.  5.  5.  5.  3.  3.]


In [14]:
X = [1,2,3,4,5,6]
I = [1,2,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 2. 4. 5. 0. 0. 0. 0. 3.]


In [20]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#print(I)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n= len(np.unique(F))
print(n)

8


In [29]:
A = np.random.randint(0,10,(2,2,2,2))


sum = A.sum(axis=(-2,-1))
print(sum)

sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[16 22]
 [11 25]]
[[16 22]
 [11 25]]


In [32]:
D = np.random.uniform(0,1,100)

S = np.random.randint(0,10,100)

D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.49394918 0.55795474 0.60466837 0.57108936 0.67220466 0.36674836
 0.38532058 0.55260972 0.43854414 0.62808154]


In [37]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.diag(np.dot(A, B))
print(A,B)

[[0.63050166 0.08747494 0.15754785 0.82255004 0.10153274]
 [0.55048953 0.25773324 0.44786866 0.13525682 0.17678999]
 [0.39396416 0.58708495 0.02380684 0.62679005 0.47387201]
 [0.16581814 0.98161342 0.0390179  0.61911644 0.89017532]
 [0.12332873 0.05571328 0.00378683 0.67580653 0.87730802]] [[0.03578307 0.4699056  0.12621269 0.26242744 0.58958717]
 [0.03310825 0.87009868 0.57784945 0.6125584  0.9730523 ]
 [0.37792161 0.58847695 0.16032053 0.74537763 0.86249327]
 [0.72028314 0.02981663 0.45594473 0.6391026  0.02066929]
 [0.21472469 0.53507541 0.16875849 0.03719753 0.96329981]]


In [39]:
arr = np.array([1,2,3,4,5])
nz = 3
arr0 = np.zeros(len(arr)+(len(arr)-1)*nz)
print(arr0)
arr0[::nz+1] = arr
print(arr0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [13]:
A = np.ones((4,4,3))
#print(A)
B = 2*np.ones((4,4))
#print(B)

print(A*B[:,:,None]) 


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [27]:
arr = np.random.randint(1,10,(5,5))
print(arr)
arr[[0,1]] = arr[[1,0]] #[0,1] = нулевая и первая строка
#print(arr[[0,1]])# = arr[[1,0]]
print("\n",arr,"\n")


[[1 6 3 3 1]
 [7 3 3 5 5]
 [9 2 1 7 8]
 [2 8 2 7 9]
 [2 5 2 5 4]]

 [[7 3 3 5 5]
 [1 6 3 3 1]
 [9 2 1 7 8]
 [2 8 2 7 9]
 [2 5 2 5 4]] 



In [28]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 17) ( 1, 63) ( 3, 66) ( 3, 88) ( 5, 12) ( 5, 41) ( 7, 13) ( 7, 95)
 (12, 41) (13, 95) (17, 63) (22, 32) (22, 85) (30, 46) (30, 49) (32, 43)
 (32, 56) (32, 85) (43, 56) (46, 49) (50, 71) (50, 93) (57, 58) (57, 99)
 (58, 99) (66, 88) (67, 74) (67, 86) (71, 93) (74, 86)]


In [30]:
a = np.bincount([1,1,2,3,4,4,5,6])
print(a)
b = np.repeat(np.arange(len(a)),a)
print(b)

[0 2 1 1 2 1 1]
[1 1 2 3 4 4 5 6]


In [3]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [2]:
from numpy.lib import stride_tricks

def rolling(a, vield):
    shape = (a.size - vield + 1, vield)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
arr = rolling(np.arange(10), 3)
print(arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [3]:
arr = np.random.randint(0,2,100)
np.logical_not(arr, out=arr)
print(arr)
arr = np.random.uniform(-1.0,1.0,100)
np.negative(arr, out=arr)
print(arr)

[1 1 1 0 1 1 0 0 0 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0
 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1 0 0 1 1 1 0
 1 0 1 0 1 1 1 0 0 0 1 0 1 0 1 1 1 0 0 1 0 1 1 0 0 0]
[-0.21158981  0.13098551 -0.75734918 -0.91114557  0.73157528  0.91441913
  0.54341833 -0.83492146  0.50630621 -0.6190264  -0.96181215  0.07655931
  0.73342826  0.40199394  0.96760374 -0.70208635  0.8583744   0.13027511
  0.06757093 -0.61074005  0.27560497 -0.42152371  0.006142    0.14710902
 -0.30317964  0.67707627 -0.8725268   0.93265282 -0.13473102 -0.22820871
 -0.65393776  0.99011715  0.16973582 -0.85176966  0.49841812 -0.80612055
 -0.65373142 -0.6768308   0.01775753  0.23435787 -0.39878042  0.33222581
  0.547201   -0.62858375  0.03778469 -0.80389658  0.7662586  -0.15569709
  0.74945949 -0.6070143  -0.00916948 -0.42384457 -0.27258937 -0.93399203
 -0.29988641 -0.23035763 -0.10933884  0.34583729 -0.8013426  -0.39822826
  0.35578699  0.55010026  0.76553858 -0.67341629 -0.61393811 -0.27

In [4]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[5.23070987 0.63865845 8.44624645 4.42552858 6.01379769 6.70745282
 4.04708301 0.25207629 2.06294457 3.97936301]


In [5]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[2.71723048e+00 7.69993118e-01 1.17741025e+01 8.90679515e+00
  1.25421917e+01 5.82733751e+00 1.12795607e+00 1.10701850e+00
  3.37157466e+00 3.94363203e+00]
 [1.83358596e+00 1.18182149e+01 4.65432752e+00 7.00845771e-01
  2.63518736e+00 3.53248232e+00 4.71906492e+00 2.52520311e+00
  3.17007977e+00 1.06970605e+01]
 [3.30537379e+00 8.83494131e+00 9.11227841e+00 4.95299481e+00
  4.82939293e+00 4.62056351e-01 5.96889464e-02 7.60217481e+00
  1.38439855e+00 1.32645866e+01]
 [1.29408671e+00 1.28512319e+01 4.31197674e+00 2.28916212e-01
  4.38631779e+00 4.14547032e+00 4.91304715e+00 3.34171911e+00
  3.44459781e+00 1.24256398e+01]
 [4.09191443e+00 1.23396098e+00 1.40951800e+01 1.04774158e+01
  2.90560232e+00 6.55212537e+00 4.27886678e+00 6.87455284e+00
  6.07586279e+00 5.91440297e+00]
 [6.71537470e+00 6.70975299e+00 2.02359782e+01 1.70281299e+01
  9.03880485e+00 1.35151181e+01 9.91570533e+00 8.11409779e+00
  1.19907428e+01 2.66266100e-01]
 [5.99059120e-01 1.02089489e+01 6.88322538e+00 2.84812824e

In [6]:
arr = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=arr.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(arr.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = arr[z]
print(arr)
print(R)

[[4 8 0 0 4 1 1 3 0 6]
 [7 9 0 2 6 4 8 9 7 4]
 [8 9 4 8 9 3 5 2 4 3]
 [8 7 9 9 2 0 1 6 8 6]
 [2 0 6 5 5 4 8 0 5 2]
 [4 5 9 8 9 2 1 9 9 1]
 [0 6 8 4 5 3 6 3 6 2]
 [7 8 5 3 8 3 5 1 2 5]
 [2 3 2 5 5 4 3 9 5 0]
 [3 4 2 7 4 9 2 1 2 4]]
[[0 0 0 0 0]
 [0 4 8 0 0]
 [0 7 9 0 2]
 [0 8 9 4 8]
 [0 8 7 9 9]]


<ipython-input-6-c205cdb37e8e>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = arr[z]


In [7]:
arr = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(arr,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [8]:
mx = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(mx) 
rank = np.sum(S > 1e-10)
print(rank)

10


In [9]:
arr = np.random.randint(0,10,50)
print(np.bincount(arr).argmax())

4


In [10]:
mx = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (mx.shape[0]-3)
j = 1 + (mx.shape[1]-3)
C = stride_tricks.as_strided(mx, shape=(i, j, n, n), strides=mx.strides + mx.strides)
print(C)

[[[[2 1 1]
   [3 2 2]
   [0 3 3]]

  [[1 1 2]
   [2 2 0]
   [3 3 0]]

  [[1 2 3]
   [2 0 4]
   [3 0 0]]

  [[2 3 3]
   [0 4 4]
   [0 0 1]]

  [[3 3 3]
   [4 4 0]
   [0 1 0]]

  [[3 3 4]
   [4 0 0]
   [1 0 0]]

  [[3 4 4]
   [0 0 0]
   [0 0 3]]

  [[4 4 4]
   [0 0 3]
   [0 3 3]]]


 [[[3 2 2]
   [0 3 3]
   [2 3 0]]

  [[2 2 0]
   [3 3 0]
   [3 0 0]]

  [[2 0 4]
   [3 0 0]
   [0 0 1]]

  [[0 4 4]
   [0 0 1]
   [0 1 2]]

  [[4 4 0]
   [0 1 0]
   [1 2 2]]

  [[4 0 0]
   [1 0 0]
   [2 2 2]]

  [[0 0 0]
   [0 0 3]
   [2 2 3]]

  [[0 0 3]
   [0 3 3]
   [2 3 2]]]


 [[[0 3 3]
   [2 3 0]
   [0 3 1]]

  [[3 3 0]
   [3 0 0]
   [3 1 3]]

  [[3 0 0]
   [0 0 1]
   [1 3 3]]

  [[0 0 1]
   [0 1 2]
   [3 3 0]]

  [[0 1 0]
   [1 2 2]
   [3 0 3]]

  [[1 0 0]
   [2 2 2]
   [0 3 0]]

  [[0 0 3]
   [2 2 3]
   [3 0 0]]

  [[0 3 3]
   [2 3 2]
   [0 0 0]]]


 [[[2 3 0]
   [0 3 1]
   [4 4 3]]

  [[3 0 0]
   [3 1 3]
   [4 3 2]]

  [[0 0 1]
   [1 3 3]
   [3 2 4]]

  [[0 1 2]
   [3 3 0]
   [2 4 2]]

  [[1 2 2]
   

In [11]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0 12 17  8 10]
 [12  0 14 13  8]
 [17 14  4 42 17]
 [ 8 13 42  7  7]
 [10  8 17  7  9]]


In [12]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [14]:
arr = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(arr, np.arange(0, arr.shape[0], k), axis=0),
                                       np.arange(0, arr.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [15]:
def iterate(Z):
   
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

   
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [16]:
a = np.arange(10000)
np.random.shuffle(a)
n = 5


print (a[np.argsort(a)[-n:]])


print (a[np.argpartition(-a,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9997 9998 9996 9995]


In [17]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [18]:
A = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(A.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [21]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 3 5 7]


In [22]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 0 4]
 [2 2 2]
 [4 3 3]
 [0 1 3]
 [0 0 1]
 [4 0 2]
 [2 3 0]
 [2 3 3]
 [2 1 3]
 [0 4 2]]
[[0 0 4]
 [4 3 3]
 [0 1 3]
 [0 0 1]
 [4 0 2]
 [2 3 0]
 [2 3 3]
 [2 1 3]
 [0 4 2]]
[[0 0 4]
 [4 3 3]
 [0 1 3]
 [0 0 1]
 [4 0 2]
 [2 3 0]
 [2 3 3]
 [2 1 3]
 [0 4 2]]


In [23]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [24]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [25]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)   
np.einsum('i,j->ij', A, B)    

array([[0.12070993, 0.01808574, 0.23387951, 0.14601822, 0.2708341 ,
        0.21135428, 0.12623869, 0.11718106, 0.2131332 , 0.22754623],
       [0.25045518, 0.03752523, 0.48526528, 0.30296613, 0.56194056,
        0.43852876, 0.26192654, 0.24313331, 0.44221976, 0.47212464],
       [0.12575611, 0.0188418 , 0.24365666, 0.15212239, 0.28215611,
        0.22018978, 0.131516  , 0.12207973, 0.22204307, 0.23705862],
       [0.06339916, 0.00949898, 0.12283798, 0.07669155, 0.14224723,
        0.1110073 , 0.06630296, 0.06154573, 0.11194162, 0.11951161],
       [0.1547104 , 0.02317997, 0.29975657, 0.1871473 , 0.34712019,
        0.27088663, 0.16179645, 0.15018756, 0.27316662, 0.29163938],
       [0.21763261, 0.03260749, 0.42167044, 0.2632619 , 0.4882973 ,
        0.38105882, 0.22760062, 0.21127028, 0.38426611, 0.41025191],
       [0.03669775, 0.00549835, 0.07110311, 0.04439187, 0.08233789,
        0.06425508, 0.03837858, 0.03562491, 0.0647959 , 0.06917769],
       [0.04888567, 0.00732445, 0.0947176

In [30]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
print(r_int)
x_int = np.interp(r_int, r, x)       
print(x_int)
y_int = np.interp(r_int, r, y)
print(y_int)

[  0.           2.48788858   4.97577716   7.46366574   9.95155432
  12.43944289  14.92733147  17.41522005  19.90310863  22.39099721
  24.87888579  27.36677437  29.85466295  32.34255152  34.8304401
  37.31832868  39.80621726  42.29410584  44.78199442  47.269883
  49.75777158  52.24566016  54.73354873  57.22143731  59.70932589
  62.19721447  64.68510305  67.17299163  69.66088021  72.14876879
  74.63665736  77.12454594  79.61243452  82.1003231   84.58821168
  87.07610026  89.56398884  92.05187742  94.539766    97.02765457
  99.51554315 102.00343173 104.49132031 106.97920889 109.46709747
 111.95498605 114.44287463 116.9307632  119.41865178 121.90654036
 124.39442894 126.88231752 129.3702061  131.85809468 134.34598326
 136.83387184 139.32176041 141.80964899 144.29753757 146.78542615
 149.27331473 151.76120331 154.24909189 156.73698047 159.22486904
 161.71275762 164.2006462  166.68853478 169.17642336 171.66431194
 174.15220052 176.6400891  179.12797768 181.61586625 184.10375483
 186.59164341

In [31]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [32]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.11179879  0.27683941]
