In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramsMy/Anaconda/coda\\Library\\include']


In [3]:
arr = np.zeros(100)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [4]:
arr = np.zeros((100,100))
#print(arr)
print("%d bytes" % (arr.size * arr.itemsize))

80000 bytes


In [5]:
arr = np.zeros(10)
arr[5] = 1
print(arr)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [6]:
arr = np.arange(0,30)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [7]:
arr = arr[::-1]
print(arr)

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]


In [8]:
arr = np.arange(12)
arr = arr.reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [9]:
arr = np.nonzero([0,0,1,2,3,1,10,0,0,1,2,3,10,1])
print(arr)

(array([ 2,  3,  4,  5,  6,  9, 10, 11, 12, 13], dtype=int64),)


In [10]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.21069391 0.74964389 0.6930656 ]
  [0.87458437 0.47348539 0.72766331]
  [0.3939478  0.11351463 0.20742699]]

 [[0.68434051 0.40955646 0.67127346]
  [0.83462585 0.38989027 0.94950569]
  [0.71838161 0.37329399 0.33234579]]

 [[0.35790062 0.61121257 0.48796176]
  [0.41455996 0.17394995 0.82623845]
  [0.76735222 0.95159751 0.57679183]]]


In [12]:
arr = np.random.random((10,10,10))
arr_min, arr_max = arr.min(), arr.max()
#print(arr)
print(arr_min, arr_max)

0.0027965580664272016 0.997521805800632


In [13]:
arr = np.random.random(30)
mean = arr.mean() #среднее
print(mean)

0.5852327283646641


In [14]:
arr = np.ones((10,10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
#arr = np.zeros((5,5))
#arr[1:-1, 1:-1] = 1
arr = np.ones((5,5))
arr = np.pad(arr, pad_width = 1, mode = 'constant', constant_values= 0)
print(arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [17]:
arr = np.diag(1+np.arange(4), k = -1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [18]:
arr = np.zeros((8,8))
arr[1::2,::2 ] = 1 #1 -[с какой начинается :: интервал, :] 
arr[::2, 1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [19]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [20]:
arr = np.tile(np.array([[1,0],[0,1]]), (4,4)) #повторяет какой либо массив 4х4 раза
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [21]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
print(arr)

[[ 0.81596001  1.06190416  1.06034175  1.44203771 -1.22605449]
 [ 1.30204145 -0.56341847 -1.66711951  1.08663916 -0.50437271]
 [-0.28810446  0.98362492  0.65407617 -0.79746026  0.73360691]
 [-0.32717833 -1.7155593   0.63634097 -0.34645725 -0.42616259]
 [-1.47358229 -0.05564125 -1.64660364  0.93226294  0.3288784 ]]


In [22]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-22-5432efe93e2f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [23]:
arr1 = np.array([[1,2,3],[13,4,3],[1,5,6], [1,8,9], [0,2,11]])
arr2 = np.array([[1,9],[0,2], [98,1]])


arr = np.dot(arr1,arr2)
print(arr)

[[ 295   16]
 [ 307  128]
 [ 589   25]
 [ 883   34]
 [1078   15]]


In [24]:
arr = np.arange(11)

arr[(3<arr)&(arr<=8)]*=-1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [25]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [26]:
Z = np.array(100)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>ZeroDivisionError

False

In [27]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-27-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-27-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [28]:
arr = np.random.uniform(-10,+10,10)
print(arr)
print (np.copysign(np.ceil(np.abs(arr)), arr))

[ 6.33557867  0.25584471  6.91229844 -1.36388236 -1.05498896  9.6298834
 -5.78618304  5.39090379  4.41698407 -6.93408247]
[ 7.  1.  7. -2. -2. 10. -6.  6.  5. -7.]


In [30]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

print(arr1, arr2)
print(np.intersect1d(arr1,arr2))

[9 2 1 6 5 6 2 1 4 2] [7 0 0 4 9 4 7 6 5 0]
[4 5 6 9]


In [31]:

defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0


_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-31-efc4639271dd>, line 7)

In [33]:
np.sqrt(-1) == np.emath.sqrt(-1)
print(np.sqrt(-1),np.emath.sqrt(-1) )

nan 1j


<ipython-input-33-8a1c3b0c741f>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)
<ipython-input-33-8a1c3b0c741f>:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1),np.emath.sqrt(-1) )


In [36]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(yesterday, today, tomorrow)

2021-10-13 2021-10-14 2021-10-15


In [37]:
data = np.arange('1999-08', '1999-09', dtype = 'datetime64[D]')
print(data)

['1999-08-01' '1999-08-02' '1999-08-03' '1999-08-04' '1999-08-05'
 '1999-08-06' '1999-08-07' '1999-08-08' '1999-08-09' '1999-08-10'
 '1999-08-11' '1999-08-12' '1999-08-13' '1999-08-14' '1999-08-15'
 '1999-08-16' '1999-08-17' '1999-08-18' '1999-08-19' '1999-08-20'
 '1999-08-21' '1999-08-22' '1999-08-23' '1999-08-24' '1999-08-25'
 '1999-08-26' '1999-08-27' '1999-08-28' '1999-08-29' '1999-08-30'
 '1999-08-31']


In [38]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [40]:
arr = np.random.uniform(0,10,10)
#print(arr)

print (arr - arr%1)
print (np.floor(arr))
print (np.ceil(arr)-1)
print (arr.astype(int))
print (np.trunc(arr))

[1. 8. 4. 5. 5. 4. 8. 8. 5. 9.]
[1. 8. 4. 5. 5. 4. 8. 8. 5. 9.]
[1. 8. 4. 5. 5. 4. 8. 8. 5. 9.]
[1 8 4 5 5 4 8 8 5 9]
[1. 8. 4. 5. 5. 4. 8. 8. 5. 9.]


In [46]:
arr = np.zeros((5,5))
#for i in range(5):
    #arr[i] = np.arange(5)
arr+=np.arange(5)    
   
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [47]:
def generate():
    for x in range(10):
        yield x
arr = np.fromiter(generate(),dtype=float,count=-1) #оздайте новый одномерный массив из итерируемого объекта.
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [50]:
arr = np.linspace(0,1,11,endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [51]:
arr = np.random.random(10)
arr.sort()
print(arr)

[0.10259751 0.23087163 0.45447035 0.47128574 0.61876841 0.63616001
 0.73937114 0.84513296 0.87967604 0.91346505]


In [3]:
arr = np.arange(10)
print(arr)
print(np.add.reduce(arr))


[0 1 2 3 4 5 6 7 8 9]
45


In [6]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

print("Форма -",np.allclose(arr1,arr2))
print("Значение -",np.array_equal(arr1,arr2))

Форма - False
Значение - False


In [7]:
arr = np.zeros(10)
arr.flags.writeable = False
arr[0] = 1

ValueError: assignment destination is read-only

In [16]:
mx = np.random.random((10,2))

print(mx)
X,Y = mx[:,0],mx[:,1] 

R = np.sqrt(X**2+Y**2)
T = np.arctan2(X,Y)
print(R,T)

mx[:,0], mx[:,1] = R,T
print(mx)

[[0.03912312 0.50055495]
 [0.68721046 0.0169286 ]
 [0.26543218 0.9562529 ]
 [0.3703807  0.11228856]
 [0.23086002 0.21389533]
 [0.18662366 0.15107566]
 [0.45137025 0.74566128]
 [0.81508854 0.88251099]
 [0.46931999 0.59493878]
 [0.43219027 0.37678542]]
[0.50208155 0.68741894 0.99240811 0.38702788 0.31471822 0.24010882
 0.87163401 1.2013305  0.7577687  0.5733722 ] [0.07800091 1.54616751 0.27075886 1.27643322 0.82352355 0.89027716
 0.54432853 0.74570268 0.66790771 0.85377904]
[[0.50208155 0.07800091]
 [0.68741894 1.54616751]
 [0.99240811 0.27075886]
 [0.38702788 1.27643322]
 [0.31471822 0.82352355]
 [0.24010882 0.89027716]
 [0.87163401 0.54432853]
 [1.2013305  0.74570268]
 [0.7577687  0.66790771]
 [0.5733722  0.85377904]]


In [18]:
arr = np.random.random(5)
print(arr)
arr[arr.argmax()] = 0
print(arr)

[0.60464971 0.75268092 0.04163541 0.40412845 0.49628537]
[0.60464971 0.         0.04163541 0.40412845 0.49628537]


In [20]:
arr = np.zeros((5,5), [('x',float),('y',float)])
print(arr)
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(arr)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [26]:
X = np.random.randint(0,10,10)
Y = np.random.randint(0,10,10)
print(X,Y)

print(np.subtract.outer(X,Y))
C = 1.0/np.subtract.outer(X,Y)
print(C)

[3 6 1 7 2 9 2 1 6 9] [5 8 8 5 1 3 3 9 5 8]
[[-2 -5 -5 -2  2  0  0 -6 -2 -5]
 [ 1 -2 -2  1  5  3  3 -3  1 -2]
 [-4 -7 -7 -4  0 -2 -2 -8 -4 -7]
 [ 2 -1 -1  2  6  4  4 -2  2 -1]
 [-3 -6 -6 -3  1 -1 -1 -7 -3 -6]
 [ 4  1  1  4  8  6  6  0  4  1]
 [-3 -6 -6 -3  1 -1 -1 -7 -3 -6]
 [-4 -7 -7 -4  0 -2 -2 -8 -4 -7]
 [ 1 -2 -2  1  5  3  3 -3  1 -2]
 [ 4  1  1  4  8  6  6  0  4  1]]
[[-0.5        -0.2        -0.2        -0.5         0.5                inf
          inf -0.16666667 -0.5        -0.2       ]
 [ 1.         -0.5        -0.5         1.          0.2         0.33333333
   0.33333333 -0.33333333  1.         -0.5       ]
 [-0.25       -0.14285714 -0.14285714 -0.25               inf -0.5
  -0.5        -0.125      -0.25       -0.14285714]
 [ 0.5        -1.         -1.          0.5         0.16666667  0.25
   0.25       -0.5         0.5        -1.        ]
 [-0.33333333 -0.16666667 -0.16666667 -0.33333333  1.         -1.
  -1.         -0.14285714 -0.33333333 -0.16666667]
 [ 0.25        1.    

<ipython-input-26-19a48a744776>:6: RuntimeWarning: divide by zero encountered in true_divide
  C = 1.0/np.subtract.outer(X,Y)


In [27]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [38]:
#вывод числе с плавоющей точкой
np.set_printoptions(threshold=10)
Z = np.zeros((5,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
#Найти ближайший элемент массива к числу
arr = np.arange(10)
print(arr)
v = np.random.uniform(0,10)
print(v)
index = (np.abs(arr-v)).argmin()
print(arr[index])

[0 1 2 ... 7 8 9]
4.712314828375747
5


In [42]:
arr = np.zeros(10, [('koordinats',[('x', float,1), ('y', float, 1)]),
                    ('color',[('r', float,1),
                              ('b', float, 1),
                              ('g', float,1)])])
print(arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-42-601abac7313f>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  arr = np.zeros(10, [('koordinats',[('x', float,1), ('y', float, 1)]),


In [51]:

#Найти растояние между точками
arr = np.random.random((10,2))
print(arr)

X,Y = arr[:,0], arr[:,1]
print(X,Y)

D = np.sqrt(X**2+Y**2)
D2 = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print("D1 ",D)
print("D2 ", D2)


import scipy
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.89805651 0.77941781]
 [0.922091   0.88513452]
 [0.97567582 0.72161638]
 ...
 [0.77425692 0.7723577 ]
 [0.12460708 0.20067824]
 [0.74711234 0.17000031]]
[0.89805651 0.922091   0.97567582 0.01172815 0.73834341 0.11145368
 0.43610481 0.77425692 0.12460708 0.74711234] [0.77941781 0.88513452 0.72161638 0.36678413 0.38839552 0.39405842
 0.26127901 0.7723577  0.20067824 0.17000031]
D1  [1.18911631 1.27816859 1.2135376  0.36697159 0.83426738 0.40951674
 0.50838384 1.09362251 0.23621744 0.76620947]
D2  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0.         0.76197249 0.65813389 ... 0.54264042 0.65481722 0.61528625]
 [0.76197249 0.         0.61022984 ... 0.57186886 0.5282975  0.27455043]
 [0.65813389 0.61022984 0.         ... 0.11693375 0.0835029  0.33997131]
 ...
 [0.54264042 0.57186886 0.11693375 ... 0.         0.12607368 0.29813356]
 [0.65481722 0.5282975  0.0835029  ... 0.12607368 0.         0.2609501 ]
 [0.61528625 0.27455043 0.33997131 ... 0.29813356 0.2609501  0.        ]]


In [52]:
#Изменить тип данных
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-54-4a7b0d9b8ca3>:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


In [57]:
arr = np.arange(9).reshape(3,3)
print(arr)
for index, value in np.ndenumerate(arr):
    print(index, value)
for index in np.ndindex(arr.shape):
    print(index, arr[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [62]:
X,Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))

D = np.sqrt(X,Y)

sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[       nan        nan        nan ... 0.75746513 0.67780958 0.60653066]
 [       nan        nan        nan ... 0.75746513 0.67780958 0.60653066]
 [       nan        nan        nan ... 0.75746513 0.67780958 0.60653066]
 ...
 [       nan        nan        nan ... 0.75746513 0.67780958 0.60653066]
 [       nan        nan        nan ... 0.75746513 0.67780958 0.60653066]
 [       nan        nan        nan ... 0.75746513 0.67780958 0.60653066]]


<ipython-input-62-7b3226622841>:3: RuntimeWarning: invalid value encountered in sqrt
  D = np.sqrt(X,Y)


In [69]:
n = 10
p = 3
arr = np.zeros((n,n))

np.put(arr,np.random.choice(range(n*n), p, replace=False),1)
print(arr)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [72]:
#Вычисление среднего значения каждой строки марицы
X = np.random.rand(5,10)
Y = X.mean(axis=1, keepdims=True)
print(Y)

[[0.62213655]
 [0.37933451]
 [0.40132827]
 [0.55032122]
 [0.53783042]]


In [87]:
#Сортировака мамссива по n-ому строкам
arr = np.random.randint(0,10,(3,3))
print(arr)
sort_mx = arr[arr[:,1].argsort()]
print(sort_mx)

[[0 0 2]
 [2 5 3]
 [4 0 7]]
[[0 0 2]
 [4 0 7]
 [2 5 3]]


In [88]:
#Определить есть ли нулевые столбцы
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False
